### ISSUE TITLE
References must be unique and required for study (validation)

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/pkdb#366]
Ensure that for every PMID reference (every reference) exactly one study exists. Currently it is possible to upload multiple studies with the same reference.

**Comment by matthiaskoenig** [comment]
This creates issues if a study is not uploading on the first trial.
```
WARNING 
{
  "details": "2744070",
  "reference": "References are required to be unqiue on every study. This Reference already exist in study <Prescott1989>."
}
```

**Comment by janekg89** [comment]
should be resolved with last commit

**Comment by matthiaskoenig** [comment]
Still seeing this issue, e.g., Lau1994.
```
{
  "details": "7696381",
  "reference": "References are required to be unqiue on every study. This Reference already exist in study <Lau1994>."
}
```

**Comment by matthiaskoenig** [comment]
Still getting this issue.
To reproduce:
 ```
./docker-purge.sh
upload_choices
watch study -s ./studies/acetaminophen/Renner2007
upload_studies
```
Then I get in the upload_studies script
```
INFO Uploading [Renner2007] --> http://0.0.0.0:8000/api/v1
INFO - 0.16 [s] : Upload references
INFO - 0.09 [s] : Upload files
INFO - 0.03 [s] : Delete index
WARNING 
{
  "details": "17442681",
  "reference": "References are required to be unqiue on every study. This Reference already exist in study <Renner2007>."
}
```
I.e. if first uploading with watch_study, then running upload_study the reference error occurs.

**Comment by matthiaskoenig** [comment]
Works.

**Comment by matthiaskoenig** [comment]
Still seeing this all the time if working on studies:
```
WARNING 
{
  "details": "3191934",
  "reference": "References are required to be unqiue on every study. This Reference already exist in study <Miners1988>."
}
```
Normally have to purge everything after this happend.
